

@hostname = localhost 
@port = 5101 
@host = https://{{hostname}}:{{port}} @contentType = application/json

### GET {{host}}/api/users

### GET {{host}}/api/users/3

### DELETE {{host}}/api/users/0

### POST {{host}}/api/users Content-Type: {{contentType}}

{

    "firstname": "Anigo", "lastname": "Montoya", "id" : 43,

}

### PUT {{host}}/api/users/1 Content-Type: {{contentType}}

{
    "firstname": "Princess", "lastname": "Buttercup", "id" : 2

}
