# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Deploy

on:
  push:
    branches:
      - MJohnson-Assignment6

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Npm Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: |
        npm install
        npm run build:prod
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Publish Api
      working-directory: ./SecretSanta/src/SecretSanta.Api/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binApiMjohnson-SecretSanta

    - name: Publish Web
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/binWebMjohnson-SecretSanta

    - name: Deploy Api
      uses: azure/webapps-deploy@v2
      with:
      app-name: MJohnson-SecretSanta-Api1
      slot-name: Production
      publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4A66AD435B934220B734AF39C22A88A7 }}
      package:  ${{env.DOTNET_ROOT}}/binApiMjohnson-SecretSanta

    - name: Deploy Web
      uses: azure/webapps-deploy@v2
      with:
      app-name: Mjohnson-SecretSanta
      slot-name: Production
      publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4AF19721583A4F03BCB316008DD48E6A }}
      package: ${{env.DOTNET_ROOT}}/binWebMjohnson-SecretSanta

